# Mathematical Verification Module for siddhi question generation
"""
Safe parsing, validation and grading for arithmetic / algebra questions.

Nothing here uses eval() or sympy.parse_expr(): text is parsed with `ast` and
rebuilt node by node as sympy objects, so a student's answer can never execute
code. Only numbers, the topic's own variables, + - * / ** and parentheses are
accepted.
"""
import ast
import re

import sympy
from sympy import Rational, Symbol

MAX_EXPONENT = 12  # guards against runaway powers like 9**9**9
MAX_ABS_VALUE = 10**12  # guards against runaway values
MAX_QUESTION_LENGTH = 1000  # questions are generated by the server
MAX_ANSWER_LENGTH = 60  # student answers are short

_ALLOWED_CHARS = re.compile(r"^[0-9A-Za-z+\-*/^().\s]*$")
_AFTER_DIGIT = re.compile(r"(?<=\d)(?=[A-Za-z(])")  # 2x -> 2*x, 3( -> 3*(
_AFTER_LETTER_OR_PAREN = re.compile(r"(?<=[A-Za-z)])(?=[A-Za-z0-9(])")  # xy, )(, )x


class QuestionRejected(Exception):
    """Carries the reason an expression was refused."""


def _clean(text):
    text = str(text)
    for old, new in (("\u2212", "-"), ("\u00d7", "*"), ("\u00f7", "/")):  # − × ÷
        text = text.replace(old, new)
    return text


def _normalize(text):
    text = re.sub(r"\s+", "", text)
    text = text.replace("^", "**")
    text = _AFTER_DIGIT.sub("*", text)
    text = _AFTER_LETTER_OR_PAREN.sub("*", text)
    return text


class _Builder:
    """
    Rebuilds an ast expression as a sympy expression.

    floor : None -> no sign rule. A number -> EVERY numeric value met on the way
            (literals, unary results, each operation) must be >= floor.
            Subtraction is fine, only its result is checked.
            Symbolic parts (anything containing a variable) are not sign-checked.
    """

    def __init__(self, allowed_symbols, floor=None):
        self.symbols = {name: Symbol(name) for name in allowed_symbols}
        self.floor = floor
        self.names_used = set()
        self.name_count = 0  # occurrences of variables
        self.constant_count = 0  # occurrences of numeric literals

    def _check(self, value, what):
        if value.is_number:
            if value.is_real is not True:
                raise QuestionRejected(f"{what} is not a real number")
            if self.floor is not None and value < self.floor:
                raise QuestionRejected(
                    f"{what} {value} is below the allowed minimum {self.floor}"
                )
            if abs(value) > MAX_ABS_VALUE:
                raise QuestionRejected(f"{what} {value} is too large")
        return value

    def build(self, node):
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool) or not isinstance(node.value, (int, float)):
                raise QuestionRejected("unsupported constant")
            self.constant_count += 1
            return self._check(Rational(str(node.value)), "number")

        if isinstance(node, ast.Name):
            if node.id not in self.symbols:
                raise QuestionRejected(f"unknown variable '{node.id}'")
            self.names_used.add(node.id)
            self.name_count += 1
            return self.symbols[node.id]

        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.USub, ast.UAdd)):
            operand = self.build(node.operand)
            value = -operand if isinstance(node.op, ast.USub) else operand
            return self._check(value, "number")

        if isinstance(node, ast.BinOp):
            left = self.build(node.left)
            right = self.build(node.right)
            op = node.op

            if isinstance(op, ast.Add):
                value = left + right
            elif isinstance(op, ast.Sub):
                value = left - right
            elif isinstance(op, ast.Mult):
                value = left * right
            elif isinstance(op, ast.Div):
                if not right.is_number:
                    raise QuestionRejected("variable in a denominator")
                if right == 0:
                    raise QuestionRejected("division by zero")
                value = left / right
            elif isinstance(op, ast.Pow):
                if not right.is_Integer:
                    raise QuestionRejected("exponent must be a whole number")
                if abs(right) > MAX_EXPONENT:
                    raise QuestionRejected("exponent too large")
                if left == 0 and right < 0:
                    raise QuestionRejected("division by zero")
                value = left ** right
            else:
                raise QuestionRejected("unsupported operator")

            return self._check(value, "intermediate result")

        raise QuestionRejected("not a plain arithmetic expression")


def parse_expression(text, allowed_symbols=(), floor=None, max_length=MAX_QUESTION_LENGTH):
    """Returns (sympy_expression, builder). Raises QuestionRejected if unusable."""
    text = _clean(text)
    if len(text) > max_length:
        raise QuestionRejected("too long")
    if not _ALLOWED_CHARS.match(text):
        raise QuestionRejected("unsupported characters")

    normalized = _normalize(text)
    if normalized == "":
        raise QuestionRejected("empty")
    try:
        tree = ast.parse(normalized, mode="eval")
    except (SyntaxError, ValueError, RecursionError, MemoryError):
        raise QuestionRejected("not a plain arithmetic expression")

    builder = _Builder(allowed_symbols, floor)
    expression = builder.build(tree.body)
    return expression, builder


def check_question(expression, floor=None, allowed_symbols=(), require_symbols=False):
    """
    Validates a GENERATED question. Returns (is_usable, reason).

    floor           : None, or the lowest number allowed anywhere in the question
                      (literals, intermediate results, final answer).
    allowed_symbols : variables the topic may use; anything else is rejected.
    require_symbols : the question must contain every allowed variable
                      (algebra topics shouldn't come out as plain arithmetic).
    """
    try:
        _, builder = parse_expression(expression, allowed_symbols, floor)
    except QuestionRejected as e:
        return False, str(e)
    except Exception as e:
        return False, f"could not be checked: {e}"

    if require_symbols:
        missing = sorted(set(allowed_symbols) - builder.names_used)
        if missing:
            return False, f"missing variable(s) {missing}"
    return True, ""


def answer_is_correct(question, answer, allowed_symbols=()):
    """
    Grades a student's answer. Returns (is_correct, reason).

    Correct means: mathematically equal to the question's value AND written in
    simplified form. The second rule stops a student pasting the question back;
    it means the answer may not use more variables or numbers than the fully
    simplified result does (so "x-3" passes, "x+0-3" and "(3+x)-(5+2)" do not).
    Numbers may be integers, decimals or fractions ("7/2"); variables are
    case sensitive.
    """
    try:
        expected, _ = parse_expression(question, allowed_symbols)
        given, given_builder = parse_expression(
            answer, allowed_symbols, max_length=MAX_ANSWER_LENGTH
        )
    except QuestionRejected as e:
        return False, str(e)
    except Exception as e:
        return False, f"could not be checked: {e}"

    if sympy.expand(expected - given) != 0:
        return False, "not equal to the value of the question"

    try:
        canonical_text = sympy.sstr(sympy.expand(expected))
        _, canonical = parse_expression(canonical_text, allowed_symbols)
    except Exception as e:
        return False, f"could not be checked: {e}"

    if (
        given_builder.name_count > canonical.name_count
        or given_builder.constant_count > canonical.constant_count
    ):
        return False, "equal, but not fully simplified"
    return True, ""
